//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется Installer.rc
//
#define IDD_DIALOG_WELCOME_PAGE         129
#define IDI_APP                         130
#define IDD_DIALOG_OFFER_PAGE           131
#define IDS_WELCOME_PAGE_TITLE          136
#define IDS_WELCOME_PAGE_BODY           137
#define IDS_WELCOME_PAGE_BUTTON_NEXT    138
#define IDS_WELCOME_PAGE_BUTTON_CANCEL  139
#define IDS_WELCOME_PAGE_HEAD           140
#define IDS_OFFER_PAGE_BUTTON_ACCEPT    141
#define IDS_OFFER_PAGE_BUTTON_CANCEL    142
#define IDS_OFFER_PAGE_LICENSE          143
#define IDS_OFFER_PAGE_HEAD_ZIP         144
#define IDS_OFFER_PROGRAM_NAME_ZIP      144
#define IDS_OFFER_PAGE_HEAD_XNVIEW      145
#define IDS_OFFER_PROGRAM_NAME_XNVIEW   145
#define IDS_OFFER_PAGE_TITLE_ZIP        146
#define IDS_OFFER_PAGE_HEAD             146
#define IDS_OFFER_PAGE_TITLE_XNVIEW     147
#define IDS_OFFER_PAGE_TITLE            147
#define IDS_OFFER_PAGE_LICENSE_URL_ZIP  148
#define IDS_LICENSE_URL_ZIP             148
#define IDS_OFFER_PAGE_LICENSE_URL_XNVIEW 149
#define IDS_LICENSE_URL_XNVIEW          149
#define IDS_OFFER_PAGE_DESCRIPTION_ZIP  150
#define IDS_DESCRIPTION_ZIP             150
#define IDS_OFFER_PAGE_DESCRIPTION_XNVIEW 151
#define IDS_DESCRIPTION_XNVIEW          151
#define IDS_PATH_REGISTER_KEY_ZIP       152
#define IDS_REGISTER_VALUE_ZIP          153
#define IDS_PATH_REGISTER_KEY_XNVIEW    154
#define IDS_REGISTER_VALUE_XNVIEW       155
#define IDS_PROGRESS_PAGE_HEAD          156
#define IDS_PROGRESS_PAGE_TITLE         157
#define IDS_PROGRESS_PAGE_BODY          158
#define IDS_PROGRESS_PAGE_STATUS_DOWNLOAD 159
#define IDS_PROGRESS_PAGE_STATUS_INSTALL 160
#define IDS_INSTALLER_URL_ZIP           161
#define IDS_INSTALLER_URL_XNVIEW        162
#define IDS_EXE_INSTALLER_NAME          163
#define IDS_EXE_INSTALLER_PARAMS_ZIP    164
#define IDS_EXE_INSTALLER_PARAMS_XNVIEW 165
#define IDS_EXECUTE_ADMIN_FLAG          166
#define IDS_EXECUTE_OPEN_FLAG           167
#define IDS_PROGRESS_PAGE_STATUS_START  168
#define IDS_PROGRESS_PAGE_STATUS_END    169
#define IDS_FINISH_PAGE_HEAD            170
#define IDS_FINISH_PAGE_TITLE           171
#define IDS_FINISH_PAGE_BUTTON_EXIT     172
#define IDS_FINISH_PAGE_BODY_INSTALLED_PROGRAMS 173
#define IDS_FINISH_PAGE_BODY_BEFORE_INSTALLED_PROGRAMS 174
#define IDS_FINISH_PAGE_BODY_CANCELED_PROGRAMS 175
#define IDS_FINISH_PAGE_BODY_ERROR_INSTALLED_PROGRAMS 176
#define IDD_DIALOG_PROGRESS_PAGE        180
#define IDD_DIALOG_FINISH_PAGE          182
#define IDB_LOGO_XNVIEW                 184
#define IDB_LOGO_ZIP                    185
#define IDC_WELCOME_PAGE_PICTURE_ZIP    1002
#define IDC_WELCOME_PAGE_PICTURE_XNVIEW 1003
#define IDC_WELCOME_PAGE_STATIC_TEXT_TITLE 1004
#define IDC_WELCOME_PAGE_STATIC_TEXT_BODY 1006
#define IDC_WELCOME_PAGE_BUTTON_NEXT    1007
#define IDC_WELCOME_PAGE_BUTTON_CANCEL  1008
#define IDC_OFFER_PAGE_PICTURE          1009
#define IDC_OFFER_PAGE_MFCLINK_LICENSE  1012
#define IDC_OFFER_PAGE_STATIC_TEXT_DESCRIPTION 1013
#define IDC_OFFER_PAGE_STATIC_TEXT_TITLE 1014
#define IDC_OFFER_PAGE_BUTTON_ACCEPT    1015
#define IDC_OFFER_PAGE_BUTTON_CANCEL    1016
#define IDC_PROGRESS_PAGE_BAR           1021
#define IDC_PROGRESS_PAGE_STATIC_TEXT_TITLE 1022
#define IDC_PROGRESS_PAGE_STATIC_TEXT_BODY 1023
#define IDC_PROGRESS_PAGE_STATIC_TEXT_STATUS 1024
#define IDC_FINISH_PAGE_PICTURE_ZIP     1027
#define IDC_FINISH_PAGE_PICTURE_XNVIEW  1028
#define IDC_FINISH_PAGE_STATIC_TEXT_TITLE 1029
#define IDC_FINISH_PAGE_BUTTON_EXIT     1030
#define IDC_FINISH_PAGE_PICTURE_CONTROL_ZIP 1031
#define IDC_FINISH_PAGE_PICTURE_CONTROL_XNVIEW 1032
#define IDC_WELCOME_PAGE_PICTURE_CONTROL_ZIP 1033
#define IDC_WELCOME_PAGE_PICTURE_CONTROL_XNVIEW 1034
#define IDC_FINISH_PAGE_STATIC_TEXT_BODY 1035

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1036
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
