//{{NO_DEPENDENCIES}}
// Включаемый файл, созданный в Microsoft Visual C++.
// Используется Installer.rc
//
#define IDD_DIALOG_WELCOME_PAGE         129
#define IDI_APP                         130
#define IDD_DIALOG_OFFER_PAGE           131
#define IDS_PATH_LOGO_ZIP               134
#define IDS_PATH_LOGO_XNVIEW            135
#define IDS_WELCOME_PAGE_TITLE          136
#define IDS_WELCOME_PAGE_BODY           137
#define IDS_WELCOME_PAGE_BUTTON_NEXT    138
#define IDS_WELCOME_PAGE_BUTTON_CANCEL  139
#define IDS_WELCOME_PAGE_HEAD           140
#define IDS_OFFER_PAGE_BUTTON_ACCEPT    141
#define IDS_OFFER_PAGE_BUTTON_CANCEL    142
#define IDS_OFFER_PAGE_LICENSE          143
#define IDS_OFFER_PAGE_HEAD_ZIP         144
#define IDS_OFFER_PAGE_HEAD_XNVIEW      145
#define IDS_OFFER_PAGE_TITLE_ZIP        146
#define IDS_OFFER_PAGE_TITLE_XNVIEW     147
#define IDS_OFFER_PAGE_LICENSE_URL_ZIP  148
#define IDS_OFFER_PAGE_LICENSE_URL_XNVIEW 149
#define IDS_OFFER_PAGE_DESCRIPTION_ZIP  150
#define IDS_OFFER_PAGE_DESCRIPTION_XNVIEW 151
#define IDS_PATH_REGISTER_KEY_ZIP       152
#define IDS_REGISTER_VALUE_ZIP          153
#define IDS_PATH_REGISTER_KEY_XNVIEW    154
#define IDS_REGISTER_VALUE_XNVIEW       155
#define IDS_PROGRESS_PAGE_HEAD          156
#define IDS_PROGRESS_PAGE_TITLE         157
#define IDS_PROGRESS_PAGE_BODY          158
#define IDD_DIALOG_PROGRESS_PAGE        180
#define IDC_WELCOME_PAGE_PICTURE_ZIP    1002
#define IDC_WELCOME_PAGE_PICTURE_XNVIEW 1003
#define IDC_WELCOME_PAGE_STATIC_TEXT_TITLE 1004
#define IDC_WELCOME_PAGE_STATIC_TEXT_BODY 1006
#define IDC_WELCOME_PAGE_BUTTON_NEXT    1007
#define IDC_WELCOME_PAGE_BUTTON_CANCEL  1008
#define IDC_OFFER_PAGE_PICTURE          1009
#define IDC_OFFER_PAGE_MFCLINK_LICENSE  1012
#define IDC_OFFER_PAGE_STATIC_TEXT_DESCRIPTION 1013
#define IDC_OFFER_PAGE_STATIC_TEXT_TITLE 1014
#define IDC_OFFER_PAGE_BUTTON_ACCEPT    1015
#define IDC_OFFER_PAGE_BUTTON_CANCEL    1016
#define IDC_PROGRESS_PAGE_BAR           1021
#define IDC_PROGRESS_PAGE_STATIC_TEXT_TITLE 1022
#define IDC_PROGRESS_PAGE_STATIC_TEXT_BODY 1023
#define IDC_PROGRESS_PAGE_STATIC_TEXT_STATUS 1024

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
